### ISSUE TITLE
Prevents breaking anything by default

### ISSUE THREAD

**Issue by Aceplante** [yzl210/HarvestLevelTweaker#1]
Even with tools, nothing can be broken at all. Even things that should not take tools like snow or leaves cannot be broken

**Comment by yzl210** [comment]
I can't reproduce. Can you provide more info?
Might be another mod preventing you from breaking blocks, like FTB Chunks, or even spawn protection of a server,

**Comment by Aceplante** [comment]
Actually yea it is still happening after disabled. Apologies. Im trying to figure it out

**Comment by Aceplante** [comment]
Cool mod tho
